(function(){"use strict";
const ICONS=[{id:"assistant",name:"Assistant"},{id:"notes",name:"Notes"},{id:"audioPlayer",name:"Audio Player"},{id:"videoPlayer",name:"Video Player"},{id:"browser",name:"Zue Browser"},{id:"controlPanel",name:"Control Panel"},{id:"trash",name:"Trash"}];
const HELP="<!DOCTYPE html><html><head><meta charset='utf-8'><title>Zue Home</title></head><body><h1>Zue Browser</h1><p>Same-origin home. Most sites block iframes. Obzue OS does not replace Windows, macOS, Android, or iOS.</p></body></html>";
class ObzueOS{
constructor(){this.apps=new Map();this.windows=new Map();this.zTop=10;this.masterVolume=1;this.trashed=[];this.settings={clock24:true,reduceMotion:matchMedia("(prefers-reduced-motion: reduce)").matches};this.boot();}
async boot(){await new Promise(r=>setTimeout(r,1100));document.getElementById("boot-screen").style.display="none";const d=document.getElementById("desktop");d.hidden=false;if(this.settings.reduceMotion)d.classList.add("reduce-motion");["assistant","notes","audioPlayer","videoPlayer","browser","controlPanel","trash"].forEach(id=>this.apps.set(id,{launch:()=>this.openApp(id)}));this.setupDesktop();this.setupMenus();this.setupTaskbar();this.setupListeners();}
setupDesktop(){const root=document.getElementById("desktop-icons");root.replaceChildren();ICONS.filter(i=>!this.trashed.includes(i.id)).forEach(icon=>{const b=document.createElement("button");b.type="button";b.className="desktop-icon";b.innerHTML='<span class="glyph">'+glyph(icon.id)+"</span><span>"+icon.name+"</span>";b.onclick=()=>this.launch(icon.id);b.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();this.showContextMenu(e.clientX,e.clientY,icon.id);};root.appendChild(b);});}
setupMenus(){const start=document.getElementById("start-menu");start.innerHTML=ICONS.map(i=>'<button type="button" class="menu-item" data-app="'+i.id+'">'+i.name+"</button>").join("")+'<div class="menu-sep"></div><button type="button" class="menu-item" data-act="about">About Obzue OS</button>';start.onclick=e=>{const b=e.target.closest("[data-app],[data-act]");if(!b)return;if(b.dataset.app)this.launch(b.dataset.app);if(b.dataset.act==="about")this.openApp("assistant");this.hideMenus();};}
setupTaskbar(){this.tickClock();setInterval(()=>this.tickClock(),1000);const slider=document.getElementById("master-volume");const box=document.getElementById("volume-slider-container");document.getElementById("volume-toggle").onclick=e=>{e.stopPropagation();box.classList.toggle("show");};slider.oninput=()=>{this.masterVolume=Number(slider.value)/100;if(window.Howler)window.Howler.volume(this.masterVolume);document.querySelectorAll("video").forEach(v=>v.volume=this.masterVolume);};}
setupListeners(){document.getElementById("start-menu-button").onclick=e=>{e.stopPropagation();this.toggleStartMenu();};document.addEventListener("click",e=>{if(!e.target.closest("#start-menu, #start-menu-button")){document.getElementById("start-menu").classList.add("hidden");}if(!e.target.closest("#volume-control"))document.getElementById("volume-slider-container").classList.remove("show");if(!e.target.closest("#context-menu"))document.getElementById("context-menu").classList.add("hidden");});document.addEventListener("contextmenu",e=>{if(e.target.closest(".window"))return;e.preventDefault();this.showContextMenu(e.clientX,e.clientY,null);});}
toggleStartMenu(){const menu=document.getElementById("start-menu");const open=menu.classList.contains("hidden");this.hideMenus();if(open)menu.classList.remove("hidden");}
hideMenus(){document.getElementById("start-menu").classList.add("hidden");document.getElementById("context-menu").classList.add("hidden");}
showContextMenu(x,y,iconId){const menu=document.getElementById("context-menu");let html="";if(iconId&&iconId!=="trash")html+='<button type="button" class="menu-item" data-app="'+iconId+'">Open</button><button type="button" class="menu-item" data-trash="'+iconId+'">Move to Trash</button>';html+='<button type="button" class="menu-item" data-app="notes">New note</button><button type="button" class="menu-item" data-act="refresh">Refresh desktop</button><button type="button" class="menu-item" data-app="assistant">About</button>';menu.innerHTML=html;menu.style.left=Math.min(x,innerWidth-240)+"px";menu.style.top=Math.min(y,innerHeight-200)+"px";menu.classList.remove("hidden");menu.onclick=e=>{const b=e.target.closest("[data-app],[data-act],[data-trash]");if(!b)return;if(b.dataset.app)this.launch(b.dataset.app);if(b.dataset.trash){this.trashed.push(b.dataset.trash);this.setupDesktop();}if(b.dataset.act==="refresh")this.setupDesktop();this.hideMenus();};}
launch(id){const a=this.apps.get(id);if(a)a.launch();}
openApp(id){const map={assistant:()=>this.makeAssistant(),notes:()=>this.makeNotes(),audioPlayer:()=>this.makeAudio(),videoPlayer:()=>this.makeVideo(),browser:()=>this.makeBrowser(),controlPanel:()=>this.makeControls(),trash:()=>this.makeTrash()};const built=map[id]();if(built)this.createWindow(built.title,built.node,id,built.onClose,built.padless);}
createWindow(title,node,appId,onClose,padless){const id="w"+Date.now().toString(16);const frame=document.createElement("div");frame.className="window";const off=24+(this.windows.size%8)*18;frame.style.left=off+"px";frame.style.top=off+"px";frame.innerHTML='<div class="window-header"><h2></h2><div class="window-controls"><button type="button" class="win-btn" data-min>-</button><button type="button" class="win-btn" data-close>x</button></div></div><div class="window-content'+(padless?" padless":"")+'"></div>';frame.querySelector("h2").textContent=title;frame.querySelector(".window-content").appendChild(node);document.getElementById("windows").appendChild(frame);const rec={id,title,el:frame,appId,onClose};this.windows.set(id,rec);this.bindWindow(rec);this.focusWindow(id);this.renderTasks();}
bindWindow(rec){rec.el.addEventListener("mousedown",()=>this.focusWindow(rec.id));rec.el.querySelector("[data-close]").onclick=()=>this.closeWindow(rec.id);rec.el.querySelector("[data-min]").onclick=()=>{rec.el.style.display="none";this.renderTasks();};let sx,sy,ox,oy,drag=false;rec.el.querySelector(".window-header").onmousedown=e=>{if(e.target.closest("button"))return;drag=true;sx=e.clientX;sy=e.clientY;ox=rec.el.offsetLeft;oy=rec.el.offsetTop;e.preventDefault();};document.addEventListener("mousemove",e=>{if(!drag)return;rec.el.style.left=ox+(e.clientX-sx)+"px";rec.el.style.top=Math.max(0,oy+(e.clientY-sy))+"px";});document.addEventListener("mouseup",()=>drag=false);}
focusWindow(id){this.zTop+=1;const rec=this.windows.get(id);if(!rec)return;rec.el.style.display="flex";rec.el.style.zIndex=String(this.zTop);this.windows.forEach(i=>i.el.classList.toggle("focused",i.id===id));this.renderTasks();}
closeWindow(id){const rec=this.windows.get(id);if(!rec)return;if(typeof rec.onClose==="function")rec.onClose();rec.el.remove();this.windows.delete(id);this.renderTasks();}
renderTasks(){const bar=document.getElementById("task-buttons");bar.replaceChildren();this.windows.forEach(rec=>{const b=document.createElement("button");b.type="button";b.className="task-btn";b.textContent=rec.title;b.onclick=()=>{if(rec.el.style.display==="none")this.focusWindow(rec.id);else if(rec.el.classList.contains("focused"))rec.el.style.display="none";else this.focusWindow(rec.id);this.renderTasks();};bar.appendChild(b);});}
tickClock(){document.getElementById("clock").textContent=new Date().toLocaleTimeString([],this.settings.clock24?{hour12:false}:{hour12:true});}
makeAssistant(){const node=document.createElement("div");node.className="stack";node.innerHTML="<p>ObzueAI assistant panel. Web desktop only. Not sentient.</p><div class='chat-log'><p>Use product-forge in Grok chat for hardware and shop packs.</p></div>";return{title:"Assistant",node};}
makeNotes(){const node=document.createElement("div");const saved=localStorage.getItem("obzue-os-notes")||"";node.innerHTML='<label class="block">Scratch pad<textarea class="notes"></textarea></label>';const area=node.querySelector("textarea");area.value=saved;area.oninput=()=>localStorage.setItem("obzue-os-notes",area.value);return{title:"Notes",node};}
makeAudio(){const node=document.createElement("div");node.className="stack";node.innerHTML='<div class="player-tools"><input type="file" accept="audio/*"><button type="button" data-play disabled>Play</button></div><p class="muted" data-status>Choose an audio file.</p>';let sound=null;const play=node.querySelector("[data-play]");node.querySelector("input").onchange=e=>{const file=e.target.files[0];if(!file||!window.Howl)return;if(sound)sound.unload();sound=new window.Howl({src:[URL.createObjectURL(file)],volume:this.masterVolume});play.disabled=false;};play.onclick=()=>{if(!sound)return;sound.playing()?sound.pause():sound.play();play.textContent=sound.playing()?"Pause":"Play";};return{title:"Audio Player",node,onClose:()=>{if(sound)sound.unload();}};}
makeVideo(){const uid="vid-"+Math.random().toString(16).slice(2);const node=document.createElement("div");node.className="stack";node.innerHTML='<input type="file" accept="video/*"><video id="'+uid+'" class="video-js vjs-default-skin" controls></video>';let player=null;node.querySelector("input").onchange=e=>{const file=e.target.files[0];if(!file||typeof videojs!=="function")return;if(player)player.dispose();player=videojs(node.querySelector("video"),{controls:true,fluid:true,sources:[{src:URL.createObjectURL(file),type:file.type||"video/mp4"}]});player.volume(this.masterVolume);};return{title:"Video Player",node,onClose:()=>{if(player)player.dispose();}};}
makeBrowser(){const node=document.createElement("div");node.style.cssText="display:flex;flex-direction:column;height:100%";node.innerHTML='<div class="browser-toolbar"><button type="button" data-home>Home</button><input type="text" data-url placeholder="Search or enter URL"><button type="button" data-go>Go</button></div><iframe class="browser-frame" sandbox="allow-scripts allow-forms allow-same-origin" title="Zue Browser"></iframe>';const frame=node.querySelector("iframe");const input=node.querySelector("[data-url]");const load=raw=>{const url=norm(raw);if(url==="about:home"){frame.srcdoc=HELP;input.value="";}else{frame.removeAttribute("srcdoc");frame.src=url;input.value=url;}};load("about:home");node.querySelector("[data-go]").onclick=()=>load(input.value);input.onkeydown=e=>{if(e.key==="Enter")load(input.value);};node.querySelector("[data-home]").onclick=()=>load("about:home");return{title:"Zue Browser",node,padless:true};}
makeControls(){const node=document.createElement("div");node.className="stack";node.innerHTML='<label><input type="checkbox" data-clock checked> 24-hour clock</label><label><input type="checkbox" data-motion> Reduce motion</label>';node.querySelector("[data-clock]").onchange=e=>{this.settings.clock24=e.target.checked;this.tickClock();};node.querySelector("[data-motion]").onchange=e=>{document.getElementById("desktop").classList.toggle("reduce-motion",e.target.checked);};return{title:"Control Panel",node};}
makeTrash(){const node=document.createElement("div");node.className="stack";if(!this.trashed.length)node.innerHTML='<p class="muted">Trash is empty.</p>';else this.trashed.forEach(id=>{const row=document.createElement("div");const b=document.createElement("button");b.textContent="Restore "+id;b.onclick=()=>{this.trashed=this.trashed.filter(x=>x!==id);this.setupDesktop();};row.appendChild(b);node.appendChild(row);});return{title:"Trash",node};}
}
function norm(raw){const t=(raw||"").trim();if(!t||t==="about:home")return"about:home";if(/^https?:\/\//i.test(t))return t;if(t.startsWith("www.")||(t.includes(".")&&!t.includes(" ")))return"https://"+t;return"https://duckduckgo.com/?q="+encodeURIComponent(t);}
function glyph(id){return({assistant:"AI",notes:"N",audioPlayer:"A",videoPlayer:"V",browser:"Z",controlPanel:"C",trash:"T"})[id]||"*";}
window.addEventListener("load",()=>{window.ObzueOS=new ObzueOS();});
})();
